query userStats ($uid: String!) {
  userStats(uid: $uid) {
    reactionsGived
    cardsCreated
    topicsCreated
    deckGived
    votesGived
    votesReceived
    likesReceived
    deckReceived
    dislikesReceived
  }
}
