query searchTag ($label: String!) {
  tagSearch(label: $label) {
    uid
    label
    topics {
      uid
      ponts
      title
      cards(page: 1) {
        count
      }
      position {
        positive
        negative
      }
      votes_topic {
        count
        positive {
          id
        }
        negative {
          id
        }
      }
      tags {
        uid
        label
      }
    }
  }
}
