query topicSearch ($filter: InputTopicFilter!) {
  topicSearch (filter: $filter) {
    count
    records {
      uid
      ponts
      title
      nickname
      url_image
      cards(page: 1) {
        count
      }
      position {
        positive
        negative
      }
      votes_topic {
        count
        positive {
          id
        }
        negative {
          id
        }
      }
      tags {
        uid
        label
      }
    }
  }
}
