query getSingleTopic ($nickname: String, $page: Int!) {
  topic (nickname: $nickname) {
    uid
    title
    content
    nickname
    url_image
    position {
      positive
      negative
    }
    author {
      name
      uid
      email
      nickname
      avatar_id
      facebook
      instagram
      site
      twitter
      youtube
    }
    tags {
      uid
      label
    }
    votes_topic {
      count
      positive {
        id
        vote
        user {
          uid
          name
          avatar_id
          nickname
        }
      }
      negative {
        id
        vote
        user {
          uid
          name
          avatar_id
          nickname
        }
      }
    }
    cards(page: $page) {
      count
      records {
        uid
        content
        position
        ponts
        has_video
        url_video
        topic {
          uid
          title
          nickname
        }
        author {
          name
          uid
          avatar_id
          nickname
        }
        deck {
          id
          user {
            uid
            name
            nickname
          }
        }
        likes {
          id
          reaction
          user {
            uid
            name
            nickname
          }
        }
        dislikes {
          id
          reaction
          user {
            uid
            nickname
            name
          }
        }
      }
    }
  }
}
