{
  topics {
    count
    mostPonts(page: 1) {
      uid
      ponts
      title
      cards(page: 1) {
        count
      }
      position {
        positive
        negative
      }
      votes_topic {
        count
        positive {
          id
        }
        negative {
          id
        }
      }
      tags {
        uid
        label
      }
    }
  }
}
