query getMiniCard ($uid: String!) {
  card(uid: $uid) {
  uid
  edited
  topic {
    uid
    title
  }
  likes {
    id
  }
  dislikes {
    id
  }
  deck {
    id
  }
  ponts
  author {
    uid
    name
  }
}
