query getSingleCard ($uid: String!) {
  card(uid: $uid) {
    uid
    content
    position
    created
    edited
    ponts
    has_video
    url_video
    topic {
      uid
      title
      nickname
      position {
        positive
        negative
      }
    }
    author {
      uid
      name
      nickname
      avatar_id
    }
    likes {
      reaction
      user {
        uid
        name
        nickname
      }
    }
    dislikes {
      reaction
      user {
        uid
        name
        nickname
      }
    }
    deck {
      user {
        uid
        name
        nickname
      }
    }
  }
}
