{
  me {
    name
    uid
    email
    avatar_id
    created
    cpf
    cep
    ponts
    facebook
    twitter
    instagram
    site
    subscriber
    administrator
    votes {
      id
      uid_topic
      vote
    }
    cards(page: 1) {
      count
      records {
        uid
        uid_topic
      }
    }
    reactions {
      id
    }
    topics(page: 1) {
      count
      records {
        uid
      }
    }
    deck {
      id
      card {
        uid
      }
    }
  }
}
