query getMyCards ($uid: String!, $page: Int!) {
  user(uid: $uid) {
    cards(page: $page) {
      count
      records {
        uid
        topic {
          uid
          title
        }
        author {
          name
          uid
          avatar_id
        }
        content
        position
        ponts
        deck {
          id
          user {
            uid
            name
          }
        }
        likes {
          id
          reaction
          user {
            uid
            name
          }
        }
        dislikes {
          id
          user {
            uid
            name
          }
        }
      }
    }
  }
}
