export { default as getUserStorage } from './getUserStorage'
export { default as getHasLogged } from './getHasLogged'
export { default as getToken } from './getToken'
export { default as isLogged } from './isLogged'
export { default as removeUser } from './removeUser'
export { default as setHasLogged } from './setHasLogged'
export { default as setUserStorage } from './setUserStorage'
export { default as setToken } from './setToken'
